
wallpaper {
    monitor = DVI-D-1
    path = /home/zach/Documents/wallpapers/end 1.png
    fit_mode = cover
}


wallpaper {
    monitor = HDMI-A-1
    path = /home/zach/Documents/wallpapers/end 3.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/zach/Documents/wallpapers/end 2.png
    fit_mode = cover
}

splash = false
