#! /usr/bin/bash


# get first listed wallpaper from hyprpaper.conf
current_wallpaper="$(echo $(cat ~/.config/hypr/hyprpaper.conf | awk -F'path = | fit_mode = cover' '{print $2}' | grep -m 1 ".png"))"

# run pywal16 with current wallpaper
wal -i "$current_wallpaper" --cols16

$terminalEmulator "pywalfox update"

# remove oomox symlink if one exists and replace with new one generated by pywal16
rm -rf ~/.config/oomox/colors/colors-oomox
ln -s ~/.cache/wal/colors-oomox ~/.config/oomox/colors/colors-oomox

# same with hyprland
ln -s ~/.cache/wal/colors-hyprland.lua ~/.config/hypr/colors-hyprland.lua

# same with vesktop if installed
rm -rf ~/.config/vesktop/themes
ln -s ~/.cache/wal/colors-discord.css ~/.config/vesktop/themes

#build theme without oomox gui
/opt/oomox/plugins/theme_oomox/change_color.sh ~/.config/oomox/colors/colors-oomox -o oomox-colors-oomox -t ~/.themes/oomox-colors-oomox



