#! /usr/bin/bash


# print wallpapers (monitor-insensitive) to file, enclose in quotes
hyprctl hyprpaper listactive | grep -o '/[^*]*' | awk '{print "\"" $0 "\""}' > ~/.config/waybar/scripts/hyprpaper_output.txt

#run imagemagick on list of files from hyprpaper output, force resize and create average wallpaper
magick composite -dissolve 100 @/home/$USER/.config/waybar/scripts/hyprpaper_output.txt -resize 1920x1080\! /home/$USER/.config/waybar/scripts/wallpaper_average.png


# run pywal16 with average wallpaper
wal -i ~/.config/waybar/scripts/wallpaper_average.png --cols16

pywalfox update

# remove oomox symlink if one exists and replace with new one generated by pywal16
rm -rf ~/.config/oomox/colors/colors-oomox
ln -s ~/.cache/wal/colors-oomox ~/.config/oomox/colors/colors-oomox

# same with hyprland
ln -s ~/.cache/wal/colors-hyprland.lua ~/.config/hypr/colors-hyprland.lua

# same with vesktop if installed
rm -rf ~/.config/vesktop/themes
ln -s ~/.cache/wal/colors-discord.css ~/.config/vesktop/themes

#build theme without oomox gui
/opt/oomox/plugins/theme_oomox/change_color.sh ~/.config/oomox/colors/colors-oomox -o oomox-colors-oomox -t ~/.themes/oomox-colors-oomox

# delete fucked up average wallpaper
rm -rf ~/.config/waybar/scripts/wallpaper_average.png


